### ISSUE TITLE
Support Warmod

### ISSUE THREAD

**Issue by ByKyTa** [Franc1sco/Franug-AutoBan-on-match-disconnect#1]
Can you support plugin Warmod (https://forums.alliedmods.net/showthread.php?p=2028726) ?

**Comment by Franc1sco** [comment]
I will see.

**Comment by Franc1sco** [comment]
Added support for Warmod.

**Comment by ByKyTa** [comment]
My server report me he warm up exit server auto ban

**Comment by ByKyTa** [comment]
WTF?
![image](https://user-images.githubusercontent.com/33537916/68770667-291f6200-0659-11ea-9fd0-62a1e874eb90.png)

**Comment by ByKyTa** [comment]
![image](https://user-images.githubusercontent.com/33537916/68770703-3b010500-0659-11ea-9ed3-2555534f820c.png)
sm_autobandisconnect_excludespectators i set 0

**Comment by ByKyTa** [comment]
![image](https://user-images.githubusercontent.com/33537916/68770720-45230380-0659-11ea-9930-0ad880931b50.png)
spec abandoned the match ?

**Comment by Franc1sco** [comment]
Plugin updated, try now.

**Comment by Franc1sco** [comment]
Ok I suppose that fixed.
